// Generated by gir (https://github.com/gtk-rs/gir @ 40843ce0ed2c)
// from /usr/share/gir-1.0 (@ ???)
// DO NOT EDIT


fn main() {
    if std::env::var("DOCS_RS").is_ok() {
        // prevent linking libraries to avoid documentation failure
        return;
    }

    if let Err(s) = system_deps::Config::new().probe() {
        println!("cargo:warning={s}");
        std::process::exit(1);
    }
}
