// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// DO NOT EDIT

use crate::{ffi};
use glib::{translate::*};


//#[doc(alias = "nautilus_module_initialize")]
//pub fn module_initialize(module: /*Ignored*/&glib::TypeModule) {
//    unsafe { TODO: call ffi:nautilus_module_initialize() }
//}

//#[doc(alias = "nautilus_module_list_types")]
//pub fn module_list_types(types: /*Unimplemented*/CArray TypeId { ns_id: 0, id: 30 }) -> i32 {
//    unsafe { TODO: call ffi:nautilus_module_list_types() }
//}

#[doc(alias = "nautilus_module_shutdown")]
pub fn module_shutdown() {
    assert_initialized_main_thread!();
    unsafe {
        ffi::nautilus_module_shutdown();
    }
}
