// Generated by gir (https://github.com/gtk-rs/gir @ 40843ce0ed2c)
// from /usr/share/gir-1.0 (@ ???)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "NautilusColumnClass", sizeof(NautilusColumnClass), alignof(NautilusColumnClass));
    printf("%s;%zu;%zu\n", "NautilusColumnProviderInterface", sizeof(NautilusColumnProviderInterface), alignof(NautilusColumnProviderInterface));
    printf("%s;%zu;%zu\n", "NautilusFileInfoInterface", sizeof(NautilusFileInfoInterface), alignof(NautilusFileInfoInterface));
    printf("%s;%zu;%zu\n", "NautilusInfoProviderInterface", sizeof(NautilusInfoProviderInterface), alignof(NautilusInfoProviderInterface));
    printf("%s;%zu;%zu\n", "NautilusMenuClass", sizeof(NautilusMenuClass), alignof(NautilusMenuClass));
    printf("%s;%zu;%zu\n", "NautilusMenuItem", sizeof(NautilusMenuItem), alignof(NautilusMenuItem));
    printf("%s;%zu;%zu\n", "NautilusMenuItemClass", sizeof(NautilusMenuItemClass), alignof(NautilusMenuItemClass));
    printf("%s;%zu;%zu\n", "NautilusMenuProviderInterface", sizeof(NautilusMenuProviderInterface), alignof(NautilusMenuProviderInterface));
    printf("%s;%zu;%zu\n", "NautilusOperationResult", sizeof(NautilusOperationResult), alignof(NautilusOperationResult));
    printf("%s;%zu;%zu\n", "NautilusPropertiesItemClass", sizeof(NautilusPropertiesItemClass), alignof(NautilusPropertiesItemClass));
    printf("%s;%zu;%zu\n", "NautilusPropertiesModelClass", sizeof(NautilusPropertiesModelClass), alignof(NautilusPropertiesModelClass));
    printf("%s;%zu;%zu\n", "NautilusPropertiesModelProviderInterface", sizeof(NautilusPropertiesModelProviderInterface), alignof(NautilusPropertiesModelProviderInterface));
    return 0;
}
