// Generated by gir (https://github.com/gtk-rs/gir @ 40843ce0ed2c)
// from /usr/share/gir-1.0 (@ ???)
// DO NOT EDIT

#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]
#![allow(clippy::approx_constant, clippy::type_complexity, clippy::unreadable_literal, clippy::upper_case_acronyms)]
#![cfg_attr(docsrs, feature(doc_cfg))]

use glib_sys as glib;
use gobject_sys as gobject;
use gio_sys as gio;

#[allow(unused_imports)]
use std::ffi::{c_int, c_char, c_uchar, c_float, c_uint, c_double,
    c_short, c_ushort, c_long, c_ulong, c_void};
#[allow(unused_imports)]
use libc::{size_t, ssize_t, time_t, off_t, intptr_t, uintptr_t, FILE};
#[cfg(unix)]
#[allow(unused_imports)]
use libc::{dev_t, gid_t, pid_t, socklen_t, uid_t};

#[allow(unused_imports)]
use glib::{gboolean, gconstpointer, gpointer, GType};

// Enums
pub type NautilusOperationResult = c_int;
pub const NAUTILUS_OPERATION_COMPLETE: NautilusOperationResult = 0;
pub const NAUTILUS_OPERATION_FAILED: NautilusOperationResult = 1;
pub const NAUTILUS_OPERATION_IN_PROGRESS: NautilusOperationResult = 2;

// Records
#[derive(Copy, Clone)]
#[repr(C)]
pub struct NautilusColumnClass {
    pub parent_class: gobject::GObjectClass,
}

impl ::std::fmt::Debug for NautilusColumnClass {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("NautilusColumnClass @ {self:p}"))
         .field("parent_class", &self.parent_class)
         .finish()
    }
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct NautilusColumnProviderInterface {
    pub g_iface: gobject::GTypeInterface,
    pub get_columns: Option<unsafe extern "C" fn(*mut NautilusColumnProvider) -> *mut glib::GList>,
}

impl ::std::fmt::Debug for NautilusColumnProviderInterface {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("NautilusColumnProviderInterface @ {self:p}"))
         .field("g_iface", &self.g_iface)
         .field("get_columns", &self.get_columns)
         .finish()
    }
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct NautilusFileInfoInterface {
    pub g_iface: gobject::GTypeInterface,
    pub is_gone: Option<unsafe extern "C" fn(*mut NautilusFileInfo) -> gboolean>,
    pub get_name: Option<unsafe extern "C" fn(*mut NautilusFileInfo) -> *mut c_char>,
    pub get_uri: Option<unsafe extern "C" fn(*mut NautilusFileInfo) -> *mut c_char>,
    pub get_parent_uri: Option<unsafe extern "C" fn(*mut NautilusFileInfo) -> *mut c_char>,
    pub get_uri_scheme: Option<unsafe extern "C" fn(*mut NautilusFileInfo) -> *mut c_char>,
    pub get_mime_type: Option<unsafe extern "C" fn(*mut NautilusFileInfo) -> *mut c_char>,
    pub is_mime_type: Option<unsafe extern "C" fn(*mut NautilusFileInfo, *const c_char) -> gboolean>,
    pub is_directory: Option<unsafe extern "C" fn(*mut NautilusFileInfo) -> gboolean>,
    pub add_emblem: Option<unsafe extern "C" fn(*mut NautilusFileInfo, *const c_char)>,
    pub get_string_attribute: Option<unsafe extern "C" fn(*mut NautilusFileInfo, *const c_char) -> *mut c_char>,
    pub add_string_attribute: Option<unsafe extern "C" fn(*mut NautilusFileInfo, *const c_char, *const c_char)>,
    pub invalidate_extension_info: Option<unsafe extern "C" fn(*mut NautilusFileInfo)>,
    pub get_activation_uri: Option<unsafe extern "C" fn(*mut NautilusFileInfo) -> *mut c_char>,
    pub get_file_type: Option<unsafe extern "C" fn(*mut NautilusFileInfo) -> gio::GFileType>,
    pub get_location: Option<unsafe extern "C" fn(*mut NautilusFileInfo) -> *mut gio::GFile>,
    pub get_parent_location: Option<unsafe extern "C" fn(*mut NautilusFileInfo) -> *mut gio::GFile>,
    pub get_parent_info: Option<unsafe extern "C" fn(*mut NautilusFileInfo) -> *mut NautilusFileInfo>,
    pub get_mount: Option<unsafe extern "C" fn(*mut NautilusFileInfo) -> *mut gio::GMount>,
    pub can_write: Option<unsafe extern "C" fn(*mut NautilusFileInfo) -> gboolean>,
}

impl ::std::fmt::Debug for NautilusFileInfoInterface {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("NautilusFileInfoInterface @ {self:p}"))
         .field("g_iface", &self.g_iface)
         .field("is_gone", &self.is_gone)
         .field("get_name", &self.get_name)
         .field("get_uri", &self.get_uri)
         .field("get_parent_uri", &self.get_parent_uri)
         .field("get_uri_scheme", &self.get_uri_scheme)
         .field("get_mime_type", &self.get_mime_type)
         .field("is_mime_type", &self.is_mime_type)
         .field("is_directory", &self.is_directory)
         .field("add_emblem", &self.add_emblem)
         .field("get_string_attribute", &self.get_string_attribute)
         .field("add_string_attribute", &self.add_string_attribute)
         .field("invalidate_extension_info", &self.invalidate_extension_info)
         .field("get_activation_uri", &self.get_activation_uri)
         .field("get_file_type", &self.get_file_type)
         .field("get_location", &self.get_location)
         .field("get_parent_location", &self.get_parent_location)
         .field("get_parent_info", &self.get_parent_info)
         .field("get_mount", &self.get_mount)
         .field("can_write", &self.can_write)
         .finish()
    }
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct NautilusInfoProviderInterface {
    pub g_iface: gobject::GTypeInterface,
    pub update_file_info: Option<unsafe extern "C" fn(*mut NautilusInfoProvider, *mut NautilusFileInfo, *mut gobject::GClosure, *mut *mut NautilusOperationHandle) -> NautilusOperationResult>,
    pub cancel_update: Option<unsafe extern "C" fn(*mut NautilusInfoProvider, *mut NautilusOperationHandle)>,
}

impl ::std::fmt::Debug for NautilusInfoProviderInterface {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("NautilusInfoProviderInterface @ {self:p}"))
         .field("g_iface", &self.g_iface)
         .field("update_file_info", &self.update_file_info)
         .field("cancel_update", &self.cancel_update)
         .finish()
    }
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct NautilusMenuClass {
    pub parent_class: gobject::GObjectClass,
}

impl ::std::fmt::Debug for NautilusMenuClass {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("NautilusMenuClass @ {self:p}"))
         .field("parent_class", &self.parent_class)
         .finish()
    }
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct NautilusMenuItemClass {
    pub parent: gobject::GObjectClass,
    pub activate: Option<unsafe extern "C" fn(*mut NautilusMenuItem)>,
}

impl ::std::fmt::Debug for NautilusMenuItemClass {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("NautilusMenuItemClass @ {self:p}"))
         .field("parent", &self.parent)
         .field("activate", &self.activate)
         .finish()
    }
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct NautilusMenuProviderInterface {
    pub g_iface: gobject::GTypeInterface,
    pub get_file_items: Option<unsafe extern "C" fn(*mut NautilusMenuProvider, *mut glib::GList) -> *mut glib::GList>,
    pub get_background_items: Option<unsafe extern "C" fn(*mut NautilusMenuProvider, *mut NautilusFileInfo) -> *mut glib::GList>,
}

impl ::std::fmt::Debug for NautilusMenuProviderInterface {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("NautilusMenuProviderInterface @ {self:p}"))
         .field("g_iface", &self.g_iface)
         .field("get_file_items", &self.get_file_items)
         .field("get_background_items", &self.get_background_items)
         .finish()
    }
}

#[repr(C)]
#[allow(dead_code)]
pub struct _NautilusOperationHandle {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

pub type NautilusOperationHandle = _NautilusOperationHandle;

#[derive(Copy, Clone)]
#[repr(C)]
pub struct NautilusPropertiesItemClass {
    pub parent_class: gobject::GObjectClass,
}

impl ::std::fmt::Debug for NautilusPropertiesItemClass {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("NautilusPropertiesItemClass @ {self:p}"))
         .field("parent_class", &self.parent_class)
         .finish()
    }
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct NautilusPropertiesModelClass {
    pub parent_class: gobject::GObjectClass,
}

impl ::std::fmt::Debug for NautilusPropertiesModelClass {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("NautilusPropertiesModelClass @ {self:p}"))
         .field("parent_class", &self.parent_class)
         .finish()
    }
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct NautilusPropertiesModelProviderInterface {
    pub g_iface: gobject::GTypeInterface,
    pub get_models: Option<unsafe extern "C" fn(*mut NautilusPropertiesModelProvider, *mut glib::GList) -> *mut glib::GList>,
}

impl ::std::fmt::Debug for NautilusPropertiesModelProviderInterface {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("NautilusPropertiesModelProviderInterface @ {self:p}"))
         .field("g_iface", &self.g_iface)
         .field("get_models", &self.get_models)
         .finish()
    }
}

// Classes
#[repr(C)]
#[allow(dead_code)]
pub struct NautilusColumn {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

impl ::std::fmt::Debug for NautilusColumn {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("NautilusColumn @ {self:p}"))
         .finish()
    }
}

#[repr(C)]
#[allow(dead_code)]
pub struct NautilusMenu {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

impl ::std::fmt::Debug for NautilusMenu {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("NautilusMenu @ {self:p}"))
         .finish()
    }
}

#[derive(Copy, Clone)]
#[repr(C)]
pub struct NautilusMenuItem {
    pub parent_instance: gobject::GObject,
}

impl ::std::fmt::Debug for NautilusMenuItem {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("NautilusMenuItem @ {self:p}"))
         .field("parent_instance", &self.parent_instance)
         .finish()
    }
}

#[repr(C)]
#[allow(dead_code)]
pub struct NautilusPropertiesItem {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

impl ::std::fmt::Debug for NautilusPropertiesItem {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("NautilusPropertiesItem @ {self:p}"))
         .finish()
    }
}

#[repr(C)]
#[allow(dead_code)]
pub struct NautilusPropertiesModel {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

impl ::std::fmt::Debug for NautilusPropertiesModel {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        f.debug_struct(&format!("NautilusPropertiesModel @ {self:p}"))
         .finish()
    }
}

// Interfaces
#[repr(C)]
#[allow(dead_code)]
pub struct NautilusColumnProvider {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

impl ::std::fmt::Debug for NautilusColumnProvider {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        write!(f, "NautilusColumnProvider @ {self:p}")
    }
}

#[repr(C)]
#[allow(dead_code)]
pub struct NautilusFileInfo {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

impl ::std::fmt::Debug for NautilusFileInfo {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        write!(f, "NautilusFileInfo @ {self:p}")
    }
}

#[repr(C)]
#[allow(dead_code)]
pub struct NautilusInfoProvider {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

impl ::std::fmt::Debug for NautilusInfoProvider {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        write!(f, "NautilusInfoProvider @ {self:p}")
    }
}

#[repr(C)]
#[allow(dead_code)]
pub struct NautilusMenuProvider {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

impl ::std::fmt::Debug for NautilusMenuProvider {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        write!(f, "NautilusMenuProvider @ {self:p}")
    }
}

#[repr(C)]
#[allow(dead_code)]
pub struct NautilusPropertiesModelProvider {
    _data: [u8; 0],
    _marker: core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}

impl ::std::fmt::Debug for NautilusPropertiesModelProvider {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        write!(f, "NautilusPropertiesModelProvider @ {self:p}")
    }
}


unsafe extern "C" {

    //=========================================================================
    // NautilusOperationResult
    //=========================================================================
    pub fn nautilus_operation_result_get_type() -> GType;

    //=========================================================================
    // NautilusColumn
    //=========================================================================
    pub fn nautilus_column_get_type() -> GType;
    pub fn nautilus_column_new(name: *const c_char, attribute: *const c_char, label: *const c_char, description: *const c_char) -> *mut NautilusColumn;

    //=========================================================================
    // NautilusMenu
    //=========================================================================
    pub fn nautilus_menu_get_type() -> GType;
    pub fn nautilus_menu_new() -> *mut NautilusMenu;
    pub fn nautilus_menu_append_item(menu: *mut NautilusMenu, item: *mut NautilusMenuItem);
    pub fn nautilus_menu_get_items(menu: *mut NautilusMenu) -> *mut glib::GList;

    //=========================================================================
    // NautilusMenuItem
    //=========================================================================
    pub fn nautilus_menu_item_get_type() -> GType;
    pub fn nautilus_menu_item_new(name: *const c_char, label: *const c_char, tip: *const c_char, icon: *const c_char) -> *mut NautilusMenuItem;
    pub fn nautilus_menu_item_list_free(item_list: *mut glib::GList);
    pub fn nautilus_menu_item_activate(item: *mut NautilusMenuItem);
    pub fn nautilus_menu_item_set_submenu(item: *mut NautilusMenuItem, menu: *mut NautilusMenu);

    //=========================================================================
    // NautilusPropertiesItem
    //=========================================================================
    pub fn nautilus_properties_item_get_type() -> GType;
    pub fn nautilus_properties_item_new(name: *const c_char, value: *const c_char) -> *mut NautilusPropertiesItem;
    pub fn nautilus_properties_item_get_name(self_: *mut NautilusPropertiesItem) -> *const c_char;
    pub fn nautilus_properties_item_get_value(self_: *mut NautilusPropertiesItem) -> *const c_char;

    //=========================================================================
    // NautilusPropertiesModel
    //=========================================================================
    pub fn nautilus_properties_model_get_type() -> GType;
    pub fn nautilus_properties_model_new(title: *const c_char, model: *mut gio::GListModel) -> *mut NautilusPropertiesModel;
    pub fn nautilus_properties_model_get_model(self_: *mut NautilusPropertiesModel) -> *mut gio::GListModel;
    pub fn nautilus_properties_model_get_title(self_: *mut NautilusPropertiesModel) -> *const c_char;
    pub fn nautilus_properties_model_set_title(self_: *mut NautilusPropertiesModel, title: *const c_char);

    //=========================================================================
    // NautilusColumnProvider
    //=========================================================================
    pub fn nautilus_column_provider_get_type() -> GType;
    pub fn nautilus_column_provider_get_columns(provider: *mut NautilusColumnProvider) -> *mut glib::GList;

    //=========================================================================
    // NautilusFileInfo
    //=========================================================================
    pub fn nautilus_file_info_get_type() -> GType;
    pub fn nautilus_file_info_create(location: *mut gio::GFile) -> *mut NautilusFileInfo;
    pub fn nautilus_file_info_create_for_uri(uri: *const c_char) -> *mut NautilusFileInfo;
    pub fn nautilus_file_info_list_copy(files: *mut glib::GList) -> *mut glib::GList;
    pub fn nautilus_file_info_list_free(files: *mut glib::GList);
    pub fn nautilus_file_info_lookup(location: *mut gio::GFile) -> *mut NautilusFileInfo;
    pub fn nautilus_file_info_lookup_for_uri(uri: *const c_char) -> *mut NautilusFileInfo;
    pub fn nautilus_file_info_add_emblem(file_info: *mut NautilusFileInfo, emblem_name: *const c_char);
    pub fn nautilus_file_info_add_string_attribute(file_info: *mut NautilusFileInfo, attribute_name: *const c_char, value: *const c_char);
    pub fn nautilus_file_info_can_write(file_info: *mut NautilusFileInfo) -> gboolean;
    pub fn nautilus_file_info_get_activation_uri(file_info: *mut NautilusFileInfo) -> *mut c_char;
    pub fn nautilus_file_info_get_file_type(file_info: *mut NautilusFileInfo) -> gio::GFileType;
    pub fn nautilus_file_info_get_location(file_info: *mut NautilusFileInfo) -> *mut gio::GFile;
    pub fn nautilus_file_info_get_mime_type(file_info: *mut NautilusFileInfo) -> *mut c_char;
    pub fn nautilus_file_info_get_mount(file_info: *mut NautilusFileInfo) -> *mut gio::GMount;
    pub fn nautilus_file_info_get_name(file_info: *mut NautilusFileInfo) -> *mut c_char;
    pub fn nautilus_file_info_get_parent_info(file_info: *mut NautilusFileInfo) -> *mut NautilusFileInfo;
    pub fn nautilus_file_info_get_parent_location(file_info: *mut NautilusFileInfo) -> *mut gio::GFile;
    pub fn nautilus_file_info_get_parent_uri(file_info: *mut NautilusFileInfo) -> *mut c_char;
    pub fn nautilus_file_info_get_string_attribute(file_info: *mut NautilusFileInfo, attribute_name: *const c_char) -> *mut c_char;
    pub fn nautilus_file_info_get_uri(file_info: *mut NautilusFileInfo) -> *mut c_char;
    pub fn nautilus_file_info_get_uri_scheme(file_info: *mut NautilusFileInfo) -> *mut c_char;
    pub fn nautilus_file_info_invalidate_extension_info(file_info: *mut NautilusFileInfo);
    pub fn nautilus_file_info_is_directory(file_info: *mut NautilusFileInfo) -> gboolean;
    pub fn nautilus_file_info_is_gone(file_info: *mut NautilusFileInfo) -> gboolean;
    pub fn nautilus_file_info_is_mime_type(file_info: *mut NautilusFileInfo, mime_type: *const c_char) -> gboolean;

    //=========================================================================
    // NautilusInfoProvider
    //=========================================================================
    pub fn nautilus_info_provider_get_type() -> GType;
    pub fn nautilus_info_provider_update_complete_invoke(update_complete: *mut gobject::GClosure, provider: *mut NautilusInfoProvider, handle: *mut NautilusOperationHandle, result: NautilusOperationResult);
    pub fn nautilus_info_provider_cancel_update(provider: *mut NautilusInfoProvider, handle: *mut NautilusOperationHandle);
    pub fn nautilus_info_provider_update_file_info(provider: *mut NautilusInfoProvider, file: *mut NautilusFileInfo, update_complete: *mut gobject::GClosure, handle: *mut *mut NautilusOperationHandle) -> NautilusOperationResult;

    //=========================================================================
    // NautilusMenuProvider
    //=========================================================================
    pub fn nautilus_menu_provider_get_type() -> GType;
    pub fn nautilus_menu_provider_emit_items_updated_signal(provider: *mut NautilusMenuProvider);
    pub fn nautilus_menu_provider_get_background_items(provider: *mut NautilusMenuProvider, current_folder: *mut NautilusFileInfo) -> *mut glib::GList;
    pub fn nautilus_menu_provider_get_file_items(provider: *mut NautilusMenuProvider, files: *mut glib::GList) -> *mut glib::GList;

    //=========================================================================
    // NautilusPropertiesModelProvider
    //=========================================================================
    pub fn nautilus_properties_model_provider_get_type() -> GType;
    pub fn nautilus_properties_model_provider_get_models(provider: *mut NautilusPropertiesModelProvider, files: *mut glib::GList) -> *mut glib::GList;

    //=========================================================================
    // Other functions
    //=========================================================================
    pub fn nautilus_module_initialize(module: *mut gobject::GTypeModule);
    pub fn nautilus_module_list_types(types: *mut *const GType, num_types: *mut c_int);
    pub fn nautilus_module_shutdown();

}
